defaults:
  - metric: insertion
  - model: vit
  - method: tis
  - dataset: ilsvrc2012_subset
  - transform: ilsvrc2012_albumentations
  - optional method_model: ${method}_${model}
  - optional metric_dataset: ${metric}_${dataset}
  - _self_

seed: 12345
no_target: false
input_npz: npz/${model.name}_${method.name}.npz
output_csv_dir: csv/
metric_batch_size: 8
start_idx: 0
end_idx: -1