defaults:
  - model: vit
  - method: tis
  - dataset: ilsvrc2012_subset
  - transform: ilsvrc2012
  - optional method_model: ${method}_${model}
  - _self_

seed: 12345
output_npz: npz/${model.name}_${method.name}.npz
