_target_: albumentations.Compose
_args_:
  - - _target_: albumentations.Normalize
      mean:
        - 0.485
        - 0.456
        - 0.406
      std:
        - 0.229
        - 0.224
        - 0.225
    - _target_: albumentations.Resize
      _args_:
        - 256
        - 256
    - _target_: albumentations.CenterCrop
      _args_:
        - 224
        - 224
    - _target_: albumentations.pytorch.ToTensorV2
bbox_params:
  _target_: albumentations.BboxParams
  format: pascal_voc

