_target_: torch.utils.data.Subset
defaults:
  - indices: sub5000.yaml
dataset:
  _target_: datasets.AlbumentationsImageNet
  root: "./inputs/imagenet/"
  split: "val"
  transform: ${transform}
name: ILSVRC2012_sub5000
